"use client";
import * as React from "react";
import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import ContextProvider from "./context/context";
import HomeNavbar from "./components/HomeNavbar";
import { usePathname } from "next/navigation";

const nunitoSans = Nunito_Sans({
  weight: "400",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Client Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname().replace("/", "");

  return (
    <html lang="en">
      <body className={nunitoSans.className}>
        <ContextProvider>
          {pathname === "" && <HomeNavbar />}
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
